#!/bin/bash

sudo apt update -y

# Install Docker
sudo apt install -y docker.io

sudo systemctl enable docker
sudo systemctl start docker

# Disable swap
sudo swapoff -a

# Install dependencies
sudo apt install -y apt-transport-https ca-certificates curl gpg

# Create keyring directory
sudo mkdir -p /etc/apt/keyrings

# Remove old files if exist
sudo rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
sudo rm -f /etc/apt/sources.list.d/kubernetes.list

# Add Kubernetes GPG key
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
sudo gpg --dearmor --batch --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# Add Kubernetes repository
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | \
sudo tee /etc/apt/sources.list.d/kubernetes.list

# Update package list
sudo apt update -y

# Install Kubernetes packages
sudo apt install -y kubelet kubeadm kubectl

# Hold versions
sudo apt-mark hold kubelet kubeadm kubectl

# Enable kubelet
sudo systemctl enable kubelet
sudo systemctl start kubelet
